### ISSUE TITLE
I tried and fail to run

### ISSUE THREAD

**Issue by Klausus** [imLinguin/nile#1]
![image](https://user-images.githubusercontent.com/2401634/162804450-60fca35b-417e-4a36-8947-a7eef62447ac.png)

Traceback (most recent call last):
  File "/home/manjaro/Desktop/amazon/nile/nile/cli.py", line 12, in <module>
    from nile.api import authorization, session, library
  File "/home/manjaro/Desktop/amazon/nile/nile/api/authorization.py", line 3, in <module>
    from gui import webview
  File "/home/manjaro/Desktop/amazon/nile/nile/gui/webview.py", line 4, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView, QWebEngineProfile, QWebEnginePage
ImportError: /home/manjaro/.local/lib/python3.10/site-packages/PyQt5/Qt5/lib/libQt5WebEngineCore.so.5: undefined symbol: _ZNSt12out_of_rangeC1EPKc, version Qt_5

**Comment by imLinguin** [comment]
Try installing `sudo pacman -S pyqt5`

**Comment by Klausus** [comment]
![image](https://user-images.githubusercontent.com/2401634/163351450-433c3cd6-1a72-42da-9a7a-465da10181a9.png)

**python-pyqt5-webengine** was the problem because is not installed by default in Manjaro (with KDE Plasma).

I installed python-pyqt5-webengine and error is not prompted, but dont show anything.

We need to write my amazon credentials in some file ??  
Or what is the problem that i dont see a gui app ??

Thanks.

**Comment by imLinguin** [comment]
GUI app is not there yet, use --help to display command line options.

You can login using `python nile/cli.py auth --login`
