### ISSUE TITLE
Missing file sds-proto2.proto in the repo

### ISSUE THREAD

**Issue by fersospe** [imLinguin/nile#10]
I found the project uses the protocol buffer compiler library from google for read the manifest binary files. I would like to have a better understanding of that part of the code, however the specs file sds-proto2.proto is not in the repository. Is it possible to add it?

**Comment by fersospe** [comment]
Never mind, I found it [here](https://github.com/derrod/twl.py/blob/master/data/proto/sds-proto2.proto).

**Comment by imLinguin** [comment]
I will add the link to that in code, for future
