### ISSUE TITLE
Not able to install on Linux Mint 21. 

### ISSUE THREAD

**Issue by KokoaNishimura** [imLinguin/nile#12]
Here are the steps I used: 

git clone https://github.com/imLinguin/nile
cd nile
pip3 install -r requirements.txt
./bin/nile auth --login

The error I get:

"Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/couper/nile/nile/cli.py", line 13, in <module>
    from nile.api import authorization, session, library
  File "/home/couper/nile/nile/api/authorization.py", line 3, in <module>
    from nile.gui import webview
  File "/home/couper/nile/nile/gui/webview.py", line 4, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView, QWebEngineProfile, QWebEnginePage
ImportError: /home/couper/.local/lib/python3.10/site-packages/PyQt5/Qt5/lib/libQt5WebEngineCore.so.5: undefined symbol: _ZNSt12out_of_rangeC1EPKc, version Qt_5"

**Comment by veganvelociraptor** [comment]
I cannot get this to work either. Tried on my Steam Deck and on my desktop computer running Arch Linux. I tried installing it by cloning the github repo, and by installing it from AUR. Everything results in the same error:

>» nile auth --login
>/home/x/.local/lib/python3.10/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.12) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
>warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
I>NFO [AUTH_MANAGER]:     Spawning login window
>
>Broadcast message from systemd-journald@x (Sat 2022-11-19 16:34:51 CET):
>
>systemd-coredump[617015]: Process 617008 (QtWebEngineProc) of user 1000 dumped core.
>Stack trace of thread 1:
>#0  0x00007f9ccf521a4d n/a (libc.so.6 + 0x108a4d)
>ELF object binary architecture: AMD x86-64

And this is how the login window looks like. I cannot do anything except close it:
![image](https://user-images.githubusercontent.com/29574272/202858961-c393d83c-0a75-4098-bebd-726fee503e03.png)

**Comment by imLinguin** [comment]
Try adding --no-sandbox parameter when launching `auth --login`

**Comment by veganvelociraptor** [comment]
> Try adding --no-sandbox parameter: `nile auth --login --no-sandbox`

Thank you. :) That worked!

**Comment by imLinguin** [comment]
QT dependency got removed now
