### ISSUE TITLE
black screen when log in auth

### ISSUE THREAD

**Issue by pepematias** [imLinguin/nile#15]
hello, when i try to login to amazon prime gaming,

![error](https://user-images.githubusercontent.com/121091386/208631026-caf0a3e6-032a-4ac9-975c-fc04ad5875aa.png)
 i get this black screen.

My system:
![os](https://user-images.githubusercontent.com/121091386/208632080-94469777-eab2-4592-b2a7-889be1c95538.png)

**Comment by imLinguin** [comment]
Try with `--no-sandbox` parameter

**Comment by brunompacheco** [comment]
I had a similar issue and `--no-sandbox` solved it.

**Comment by pepematias** [comment]
Now it works, thanks!

**Comment by imLinguin** [comment]
Removed QT dependency, no need for that anymore
