### ISSUE TITLE
No suitable graphics backend found

### ISSUE THREAD

**Issue by brunompacheco** [imLinguin/nile#16]
I installed everything through conda, fixed the "libstdc++" linking problem (see [this](https://stackoverflow.com/questions/72110384/libgl-error-mesa-loader-failed-to-open-iris)), and now, when I try to `auth --login` I get
```
No suitable graphics backend found

./bin/nile: line 4: 16315 Aborted                 (core dumped) /usr/bin/env python3 -m nile.cli "$@"
```

**Comment by brunompacheco** [comment]
I just tried with the system-wide python (installing the requirements through pip) and it worked.

**Comment by imLinguin** [comment]
Removed QT dependency this shouldn't be a issue anymore
