### ISSUE TITLE
Not really an issue just wanting help, is there anyway to change where the games are installed? I'd like to install them to an external hard drive

### ISSUE THREAD

**Issue by diavolicchio** [imLinguin/nile#17]
How do i change where the games are installed and stored?

**Comment by imLinguin** [comment]
You can provide `--base-path` argument to select the directory where the game will be downloaded to. Or `--path` for exact location


difference is that to --base-path Nile will append game specific directory

so for example if you provide --base-path `/home/user/Games` Nile will install the game to
`/home/user/Games/The Game Name`

**Comment by diavolicchio** [comment]
Thanks you
