### ISSUE TITLE
How install games?

### ISSUE THREAD

**Issue by ToMattBan** [imLinguin/nile#18]
So, I installed nile and logged successfully, but now I don't know how to use it hahaha.

The install command ask for a id (Probably of the game), where can I get this ID?

Also, if you want help to write a wiki, I can help you (after learning how to use it, ofc)

**Comment by imLinguin** [comment]
:smile: 

you can get game id from `library list` command  
If in doubt there is always `--help` for each subcommand.

For example:
```
$ nile install --help

usage: nile install [-h] [--max-workers MAX_WORKERS]
                        [--base-path BASE_PATH] [--path EXACT_PATH]
                        id

positional arguments:
  id                    Specify a ID of the game to be installed

options:
  -h, --help            show this help message and exit
  --max-workers MAX_WORKERS
                        Specify max threads to be used
  --base-path BASE_PATH
                        Specify base installation path e.g
                        /home/USERNAME/Games/nile It'll append save filename
                        to that path
  --path EXACT_PATH     Specify exact install location

```

**Comment by ToMattBan** [comment]
Nice, thank you. I will start writing something to help others that have some questions like mine XD
This will probably make your job easier haha
