### ISSUE TITLE
KeyError: 'genres' on "nile library list"

### ISSUE THREAD

**Issue by notpentadactyl** [imLinguin/nile#2]
```
./bin/nile library list
INFO [AUTH_MANAGER]:	Refreshing token
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/deck/nile/nile/cli.py", line 238, in <module>
    sys.exit(main())
  File "/home/deck/nile/nile/cli.py", line 217, in main
    cli.handle_library()
  File "/home/deck/nile/nile/cli.py", line 67, in handle_library
    games_list += f'{"(INSTALLED) " if installed_dict.get(game["id"]) and not self.arguments.installed else ""}{game["product"]["title"]} ID: {game["id"]} GENRES: {game["product"]["productDetail"]["details"]["genres"]}\n'
KeyError: 'genres'
```

As a workaround I locally removed the `{game["product"]["productDetail"]["details"]["genres"]}` part.

**Comment by imLinguin** [comment]
I guess I'll remove that part from library view for now.
Can you track down which game doesn't have genres in `~/.config/nile/library.json`?

**Comment by notpentadactyl** [comment]
These three are missing the genre field:
`Brütal Legend` `3ea9dd41-009a-4944-b23b-30d0450d3b90`
`Broken Age` `9504afc3-c0e2-478a-8dd7-03761f536363`
`Devil May Cry HD Collection:Devil May Cry HD` `c24336e8-b8e2-4537-bf1b-9f6cc6cee40a`

**Comment by imLinguin** [comment]
Just pushed the changes that should fix the issue upstream. Let me know if it works

**Comment by notpentadactyl** [comment]
That works. :+1:
