### ISSUE TITLE
FuelPump DRM

### ISSUE THREAD

**Issue by imLinguin** [imLinguin/nile#22]
Not all games are DRM free. Some require authentication from Amazon Games app to run/login to some online account. This might be a case for online games specifically.

If someone encountered a game that required it please let me know on this issue.

I'll be posting updates related to this feature here.

**Comment by cutiecactus** [comment]
This might be a dumb question, but how do I know if a game uses FuelPump? I'd like to help, but have no clue what I'm looking for

**Comment by imLinguin** [comment]
It probably won't run, or have limited online support. Hard to tell really, it may also contain some FuelPump dll

**Comment by CourteousGeek** [comment]
I'm using Heroic Game Launcher which has Nile built in and i can't seem to launch DMC1HD, it might have FuelPump DRM, looks to say fuel.json?
![cmd_xfaXUiteYU](https://github.com/imLinguin/nile/assets/77457021/364fdc1c-a822-4f05-b593-b01923ff04f0)
![notepad++_FeB1FwahTM](https://github.com/imLinguin/nile/assets/77457021/1395c280-350b-4cd0-968b-84c35cd1e294)

**Comment by imLinguin** [comment]
Indeed `AuthScopes` and `ClientId` seem to suggest it's part of the DRM logic

**Comment by imLinguin** [comment]
@CourteousGeek checkout the latest commit I believe it should resolve this

https://github.com/imLinguin/nile/actions/runs/9235859279

**Comment by CourteousGeek** [comment]
@imLinguin it works! it launches the game right away!
