### ISSUE TITLE
Steam Deck - Failed to load module "canberra-gtk-module"

### ISSUE THREAD

**Issue by smoofus** [imLinguin/nile#24]
When attempting to auth on the steam deck the browser opens but I get the following errors.

```
Paste amazon.com url you got redirected to: Gtk-Message: 10:07:23.051: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:07:23.857: Failed to load module "canberra-gtk-module" 
```

Can confirm I ran `pip3 install -r requirements.txt` but didn't see anything referencing this module.

**Comment by imLinguin** [comment]
You can safely ignore it, it's just junk that's being thrown by the browser. You should be able to paste the URL without issues.

**Comment by smoofus** [comment]
I'll be damned.  Confirmed, pasted without issue.  The error triggered me somehow that sent me down a rabbit hole and I failed to just try pasting the dang URL!  Thank you for the quick response and your awesome work!
