### ISSUE TITLE
UNINSTALL misspelled

### ISSUE THREAD

**Issue by brianpipa** [imLinguin/nile#37]
UNINSTALL misspelled:

>nile uninstall amzn1.adg.product.c42ee7aa-7704-4330-b5b8-79df1317304e
INFO [UNISNTALL]:	 Game removed successfully

**Comment by imLinguin** [comment]
welp https://github.com/imLinguin/nile/commit/623340e83c7f7737aeb0e197a31438fa1d7b0067
