### ISSUE TITLE
Game doesn't launch on Linux when fuel.json Command contains back-slashes

### ISSUE THREAD

**Issue by RParodia** [imLinguin/nile#39]
For games such as `Indiana Jones and the Last Crusade`, the "Command" part of fuel.json specifies the file path `Common\\ScummVM\\scummvm.exe`. I haven't tested it on Windows (but would imagine it might work) but obviously on Linux the back-slashes break it.

Here is the full `fuel.json`:
```
{
 "SchemaVersion":  "2",
 "PostInstall": [  ],
 "Main": {
   "Command": "Common\\ScummVM\\scummvm.exe",
   "DesktopShortcutIconFile": "Common\\ScummVM\\Indy3.ico",
   "Args": ['-c', 'last-crusade.ini', 'last-crusade']
 }
}
```
and here is the error thrown by nile:
```
ERROR:root:Executable file path does not exist or is not accessible by the Flatpak: <path to game>/Indiana Jones/Common\ScummVM\scummvm.exe
```

**Comment by imLinguin** [comment]
Did you try replacing the slashes in the `fuel.json` just to test this theory?

**Comment by RParodia** [comment]
Yes, replacing the slashes fixes it. I still have other issues with this game, but they are seperate and

**Comment by RParodia** [comment]
Sorry for closing and re-opening the issue, still getting used to Github. Yes, changing the slashes fixes the issue with finding the executable. There are other issues with launching this particular game, but I need to look more into them before I can report them.

**Comment by imLinguin** [comment]
All right, I'll try to fix it. Also since this is scummvm. I'd advise to avoid launching it through wine

**Comment by imLinguin** [comment]
I can also add automatic detection for this to provide better performance for those games

**Comment by imLinguin** [comment]
Just pushed the fixes for both, if you have scummvm installed on your machine and is in $PATH or installed in flatpak it should be used instead of trying to run it through wine
