### ISSUE TITLE
Running on a native windows machine

### ISSUE THREAD

**Issue by buswedg** [imLinguin/nile#42]
I've had some problems getting this to run on a Windows 11 machine with Python installed locally (don't have WSL on my game machine).

I assume running this on Win isn't the intended use case you're going after. But I do see something like this as being handy for my needs, where I want to bulk download all of my AmazonGames to an external drive, such that I can move a particular game over to my primary drive when I'm ready to play it.

Legendary works well for me when it comes to EpicGames. So perhaps you're moving this effort in a similar direction?

**Comment by imLinguin** [comment]
What seems to be an issue? Could you provide logs?

**Comment by buswedg** [comment]
Well, I would think the preferred way to run this on a win machine (with python available on PATH and your repo cloned to C:\nile) would be to do something like this:

```
cd C:\nile
python -m venv env
call env/Scripts/activate
pip install -r requirements.txt
python bin\nile auth --login
```

but the syntax you have on the entrypoint in bin\nile isn't going to work in windows. I don't have it in front of me right now, but  pretty sure the below line is going to give invalid syntax.

```
cd "$(dirname $(readlink -f "$0"))/.."
```

**Comment by buswedg** [comment]
Well, I would think the preferred way to run this on a win machine (with python available on PATH and your repo cloned to C:\nile) would be to do something like this:

```
cd C:\nile
python -m venv env
call env/Scripts/activate
pip install -r requirements.txt
```

but the entrypoint in bin\nile is a bash script. So, without having access to wsl. I'd assume you need to run this direct using python at nile/cli.py, but that'll throw module not found errors etc.

**Comment by buswedg** [comment]
Never mind, this actually does work per the steps I noted above.
