### ISSUE TITLE
Is it possible to get a log file when installing a game with nine?

### ISSUE THREAD

**Issue by josue2363** [imLinguin/nile#47]
Is it possible to get the output and generate a log file when installing a game with nine? I've tried many variations to get a log with download information with nine, like:

`./nile install "amzn1.adg.product.5d35cae7-39d1-4e53-ba92-36004c4a5211" > ~/log-file.log`

or

`./nile install "amzn1.adg.product.5d35cae7-39d1-4e53-ba92-36004c4a5211" > ~/log-file.log 2>&1`

and

`./nile install "amzn1.adg.product.5d35cae7-39d1-4e53-ba92-36004c4a5211" 2>&1 | (pv -n > ~/log-file.log)`

I also tried something like:

`script -q -c "./nile install "amzn1.adg.product.5d35cae7-39d1-4e53-ba92-36004c4a5211" | (pv -n > ~/log-file.log) 2>&1`

As you can see, I've already tried everything and the only things I see in the log file is the following:

_INFO [CLI]:	 Found: Baldur's Gate: Enhanced Edition
INFO [DOWNLOAD]:	 Generating patches, this might take a second..._

Am I doing something wrong or can nile not save its output to a simple log file?

**Comment by imLinguin** [comment]
I'm pretty sure the progress should get logged properly as part of stderr. The patches thing may take a bit depending on the number of game files. Are you patient enough?

**Comment by josue2363** [comment]
> I'm pretty sure the progress should get logged properly as part of stderr. The patches thing may take a bit depending on the number of game files. Are you patient enough?

Did you do a test to see if the same thing happens to you using one of the examples I gave previously? This works with legendary, but not with nile. So I need to know if I'm doing something wrong.

**Comment by imLinguin** [comment]
I just tested it and....
```
./nile install amzn1.adg.product.33c7e483-297f-48ef-95ba-411ff59ca701 &> test.log
```

```
$ head test.log 
INFO [CLI]:      Found: looK INside
INFO [DOWNLOAD]:         Generating patches, this might take a second...
INFO [DOWNLOAD]:         Download size: 560.13MB
INFO [PROGRESS]:         = Progress: 0.00 0/587335143, Running for: 00:00:00, ETA: 00:00:00
INFO [PROGRESS]:         = Downloaded: 0.00 MiB, Written: 0.00 MiB
INFO [PROGRESS]:          + Download    - 0.00 MiB/s
INFO [PROGRESS]:          + Disk        - 0.00 MiB/s
INFO [PROGRESS]:         = Progress: 0.00 0/587335143, Running for: 00:00:01, ETA: 00:00:00
INFO [PROGRESS]:         = Downloaded: 0.00 MiB, Written: 0.00 MiB
INFO [PROGRESS]:          + Download    - 0.00 MiB/s
```

**Comment by josue2363** [comment]
Okay, thanks for helping me.

You were right, I had to wait for the patches.
After waiting for patches, the log started to be generated in real time.
That was all I needed to capture the download progress.
