### ISSUE TITLE
White window when logging in with glibc >=2.35

### ISSUE THREAD

**Issue by Ryhon0** [imLinguin/nile#5]
With glibc 2.35 being released a bunch of chromium programs stopped working, including the Qt web engine.
Setting the `QTWEBENGINE_CHROMIUM_FLAGS` environment variable to `--no-sandbox` or `--disable-seccomp-filter-sandbox` makes it work again

**Comment by imLinguin** [comment]
Thanks for reporting!

**Comment by imLinguin** [comment]
I'm considering on dropping QT dependency in near future (if prompting user to open link in the browser will work as expected)

**Comment by lgaudreau** [comment]
How do you set the QTWEBENGINE_CHROMIUM_FLAGS environment variables?  I'm getting this as well.

**Comment by imLinguin** [comment]
Removed QT dependency
