### ISSUE TITLE
Windows 7 Support

### ISSUE THREAD

**Issue by narniaexpert** [imLinguin/nile#52]
This project originally was intended as an Amazon Games client for Linux based devices like Steam Deck, but it really is a multi-platform Python app that could also benefit users of older PCs no longer supported by the official Amazon Games Windows client. Sometime within the past year Amazon dropped support for Windows 7 from the official Amazon Games Windows client and requires Windows 10 to download or install new games. Most of the classic games in the Amazon Games catalog are older titles which run fine in Windows 7, so this project will benefit users of older PCs with an alternative method of downloading their collection. Since I was able to download, compile, and run this project in a Windows environment this issue primarily addresses documentation.

Documentation should be re-branded as a multi-platform Python based command line interface to download games for both Linux and older PCs. 

The latest version of Python that supports Windows 7 is Python 3.8.10 #https://www.python.org/downloads/release/python-3810/ I was able to successfully run this program using Python 3.8.10 and use pip to install pyinstaller and all required dependencies.

Instructions should be provided for Windows users who are not experienced with Python or using a command line interface. Please consider including a pre-compiled Windows executable in a future release for users who do not have this type of experience to compile their own executable using pyinstaller.

**Comment by imLinguin** [comment]
Doesn't the already provided executable work? I agree the README could be re-phrased to reflect multi platform support

**Comment by narniaexpert** [comment]
I like the changes you made to the project read me page. I hadn't seen that there was a provided executable, but for me it won't launch because I am missing python39.dll

**Comment by imLinguin** [comment]
I've updated the CI to use python 3.8. You can try the build from here https://github.com/imLinguin/nile/actions/runs/11085459577  
If it doesn't work then I'm out of ideas

**Comment by narniaexpert** [comment]
Last week I somehow got this to build myself, but now both that is broken as well as the binary you compiled and I can't get it to rebuild. In both cases the errors are something like this:

```
C:\>nile
Traceback (most recent call last):
  File "nile\cli.py", line 354, in <module>
  File "nile\cli.py", line 324, in main
  File "nile\cli.py", line 37, in __init__
  File "nile\cli.py", line 41, in __migrate_old_ids
  File "nile\utils\config.py", line 93, in get
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[PYI-2268:ERROR] Failed to execute script 'cli' due to unhandled exception!
```

I have tried re-installing python, but don't really know what is happening. Thanks for switching to python 3.8 for me.

**Comment by imLinguin** [comment]
Try cleaning the configuration directory, maybe it got corrupted somehow

**Comment by narniaexpert** [comment]
Do you have any resources to point me to about how to do that?

**Comment by imLinguin** [comment]
it should be available in standard location on windows `%APPDATA%\\nile`

**Comment by narniaexpert** [comment]
Thanks! That is exactly what I needed. The provided executable runs fine now.
