### ISSUE TITLE
Hello Problem for installation on Pop OS 22.04

### ISSUE THREAD

**Issue by ben3291** [imLinguin/nile#6]
Impossible to find the Python-Zstd package 
and at the launch of the order ~/nile$ ./bin/nile auth --login
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/benoit/nile/nile/cli.py", line 13, in <module>
    from nile.api import authorization, session, library
  File "/home/benoit/nile/nile/api/authorization.py", line 3, in <module>
    from nile.gui import webview
  File "/home/benoit/nile/nile/gui/webview.py", line 4, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView, QWebEngineProfile, QWebEnginePage
ImportError: /home/benoit/.local/lib/python3.10/site-packages/PyQt5/Qt5/lib/libQt5WebEngineCore.so.5: undefined symbol: _ZNSt12out_of_rangeC1EPKc, version Qt_5
good luck I can do nothing more I don't know how to code

**Comment by imLinguin** [comment]
There is a typo in the readme, it's `python3-zstd`

If you installed dependencies using apt, there is no need to install them with pip.

**Comment by WildWeazel** [comment]
I'm also on Pop and caught this, but then I hit this error when running:

```./bin/nile auth --login
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/travis/Games/nile/nile/cli.py", line 6, in <module>
    from PyQt5.QtWidgets import QApplication
RuntimeError: the sip module implements API v12.0 to v12.8 but the PyQt5.QtWidgets module requires API v12.9
```
This was resolved with `pip3 install PyQt5-sip --upgrade`. I don't know if that's a mistake in the Readme, or requirements.txt, or if it's something specific to Pop.

**Comment by ben3291** [comment]
Thank you I do a test

**Comment by ben3291** [comment]
benoit@pop-os-benoir-bureau:~$ sudo apt install python3-zstd
[sudo] Mot de passe de benoit : 
Désolé, essayez de nouveau.
[sudo] Mot de passe de benoit : 
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances... Fait
Lecture des informations d'état... Fait      
Les NOUVEAUX paquets suivants seront installés :
  python3-zstd
0 mis à jour, 1 nouvellement installés, 0 à enlever et 0 non mis à jour.
Il est nécessaire de prendre 251 ko dans les archives.
Après cette opération, 761 ko d'espace disque supplémentaires seront utilisés.
Réception de :1 http://apt.pop-os.org/ubuntu jammy/universe amd64 python3-zstd amd64 1.5.0.2-1build1 [251 kB]
251 ko réceptionnés en 1s (278 ko/s) 
Sélection du paquet python3-zstd précédemment désélectionné.
(Lecture de la base de données... 292570 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de .../python3-zstd_1.5.0.2-1build1_amd64.deb ...
Dépaquetage de python3-zstd (1.5.0.2-1build1) ...
Paramétrage de python3-zstd (1.5.0.2-1build1) ...
benoit@pop-os-benoir-bureau:~$ pip3 install PyQt5-sip --upgrade
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: PyQt5-sip in /usr/lib/python3/dist-packages (12.9.1)
Collecting PyQt5-sip
  Downloading PyQt5_sip-12.11.0-cp310-cp310-manylinux1_x86_64.whl (359 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 359.7/359.7 KB 3.8 MB/s eta 0:00:00
Installing collected packages: PyQt5-sip
Successfully installed PyQt5-sip-12.11.0
benoit@pop-os-benoir-bureau:~$ git clone https://github.com/imLinguin/nile
fatal: le chemin de destination 'nile' existe déjà et n'est pas un répertoire vide.
benoit@pop-os-benoir-bureau:~$ cd nile
benoit@pop-os-benoir-bureau:~/nile$ ./bin/nile auth --login
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/benoit/nile/nile/cli.py", line 13, in <module>
    from nile.api import authorization, session, library
  File "/home/benoit/nile/nile/api/authorization.py", line 3, in <module>
    from nile.gui import webview
  File "/home/benoit/nile/nile/gui/webview.py", line 4, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView, QWebEngineProfile, QWebEnginePage
ImportError: /home/benoit/.local/lib/python3.10/site-packages/PyQt5/Qt5/lib/libQt5WebEngineCore.so.5: undefined symbol: _ZNSt12out_of_rangeC1EPKc, version Qt_5


the problem and always the

**Comment by ben3291** [comment]
> benoit@pop-os-benoir-bureau:~$ sudo apt install python3-zstd
[sudo] Mot de passe de benoit : 
Désolé, essayez de nouveau.
[sudo] Mot de passe de benoit : 
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances... Fait
Lecture des informations d'état... Fait      
Les NOUVEAUX paquets suivants seront installés :
  python3-zstd
0 mis à jour, 1 nouvellement installés, 0 à enlever et 0 non mis à jour.
Il est nécessaire de prendre 251 ko dans les archives.
Après cette opération, 761 ko d'espace disque supplémentaires seront utilisés.
Réception de :1 http://apt.pop-os.org/ubuntu jammy/universe amd64 python3-zstd amd64 1.5.0.2-1build1 [251 kB]
251 ko réceptionnés en 1s (278 ko/s) 
Sélection du paquet python3-zstd précédemment désélectionné.
(Lecture de la base de données... 292570 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de .../python3-zstd_1.5.0.2-1build1_amd64.deb ...
Dépaquetage de python3-zstd (1.5.0.2-1build1) ...
Paramétrage de python3-zstd (1.5.0.2-1build1) ...
benoit@pop-os-benoir-bureau:~$ pip3 install PyQt5-sip --upgrade
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: PyQt5-sip in /usr/lib/python3/dist-packages (12.9.1)
Collecting PyQt5-sip
  Downloading PyQt5_sip-12.11.0-cp310-cp310-manylinux1_x86_64.whl (359 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 359.7/359.7 KB 3.8 MB/s eta 0:00:00
Installing collected packages: PyQt5-sip
Successfully installed PyQt5-sip-12.11.0
benoit@pop-os-benoir-bureau:~$ git clone https://github.com/imLinguin/nile
fatal: le chemin de destination 'nile' existe déjà et n'est pas un répertoire vide.
benoit@pop-os-benoir-bureau:~$ cd nile
benoit@pop-os-benoir-bureau:~/nile$ ./bin/nile auth --login
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/benoit/nile/nile/cli.py", line 13, in <module>
    from nile.api import authorization, session, library
  File "/home/benoit/nile/nile/api/authorization.py", line 3, in <module>
    from nile.gui import webview
  File "/home/benoit/nile/nile/gui/webview.py", line 4, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView, QWebEngineProfile, QWebEnginePage
ImportError: /home/benoit/.local/lib/python3.10/site-packages/PyQt5/Qt5/lib/libQt5WebEngineCore.so.5: undefined symbol: _ZNSt12out_of_rangeC1EPKc, version Qt_5

**Comment by CannonFather** [comment]
I'm also having a problem with running it under PopOS!
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/heathdelzer/nile/nile/cli.py", line 13, in <module>
    from nile.api import authorization, session, library
  File "/home/heathdelzer/nile/nile/api/authorization.py", line 3, in <module>
    from nile.gui import webview
  File "/home/heathdelzer/nile/nile/gui/webview.py", line 4, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView, QWebEngineProfile, QWebEnginePage
ImportError: libQt5WebChannel.so.5: cannot open shared object file: No such file or directory

**Comment by imLinguin** [comment]
Looks like it fails on the qt webengine dependency. 

I really need to get rid of this dependency soon

**Comment by imLinguin** [comment]
Removed QT dependency
