### ISSUE TITLE
Is it possible to Implement this into Heroic Games Launcher at some point?

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [imLinguin/nile#7]
pretty self explanatory question

**Comment by imLinguin** [comment]
I don't see a reason why not

**Comment by Gustash** [comment]
Currently working on this in https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/2831

**Comment by Gustash** [comment]
@imLinguin I think we can close this now that the PR has been merged
